### ISSUE TITLE
Integrate DuckDuckGo search

### ISSUE THREAD

**Issue by frippz** [frippz/frippz.se#39]
Check out: 
* https://web.archive.org/web/20160623174219/http://hardik.org/blog/stylising-duckduckgo-site-search/
* https://duckduckgo.com/params
* https://github.com/seanredmond/jekyll-ddg-search

```html
<form method="post" action="/search" id="search">
  <input type="search" id="search-input">
  <button>Search</button>
</form>
```

```css
#search {
  display: flex;
  position: absolute;
  top: 0;
  right: 0;
  margin: 0.5rem;
  font-size: 0.8em;
  filter: drop-shadow(0 0 0.2rem rgba(0, 0, 0, 0.1));
}

#search-input {
  border: 0;
  border-radius: 0.2rem 0rem 0rem 0.2rem;
  font: inherit;
  margin: 0;
  -webkit-appearance: none;
}

#search button {
  font: inherit;
  margin: 0;
  border-radius: 0 0.2rem 0 0.2rem;
}
```
